name: totesys-ETL

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Init
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'
      - name: Run Tests
        run: make all
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          flake8 src/* test/*
        # uses: suo/flake8-github-action@releases/v1
        # with:
        #   checkName: run-tests   # NOTE: this needs to be the same as the job name
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo the repository content
        run: |
          echo "Listing all files in the repository:"
          ls 

  deploy-infrastructure:
    name: deploy-infrastructure
    runs-on: ubuntu-latest
    needs: run-tests
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Init
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'
      - name: run make
        uses: make lambda_requirements
      - name: Echo the repository content
        run: |
          echo "Listing all files in the repository:"
          ls 
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform apply
        working-directory: terraform
        run: terraform apply --auto-approve